runtime: java
env: flex
service: gcpappenginedemoapp

automatic_scaling:
  min_num_instances: 2
  max_num_instances: 3
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.6
    
runtime_config:
   jdk: openjdk9

env_variables:
    appname: gcpappenginedemoapp
    version: master

handlers:
- url: /.*
  script: this filed is required, but ignored